// ─── Waitlist ─────────────────────────────────────────────────────────────────

export const LEVELS = [
  '100 Level',
  '200 Level',
  '300 Level',
  '400 Level',
  '500 Level',
  'Final Year',
] as const;

export const NIGERIAN_UNIVERSITIES = [
  // ─── Federal Universities ────────────────────────────────────────────────────
  'University of Abuja',
  'University of Agriculture, Abeokuta (FUNAAB)',
  'University of Agriculture, Makurdi',
  'University of Benin (UNIBEN)',
  'University of Calabar (UNICAL)',
  'University of Ibadan (UI)',
  'University of Ilorin (UNILORIN)',
  'University of Jos (UNIJOS)',
  'University of Lagos (UNILAG)',
  'University of Maiduguri (UNIMAID)',
  'University of Nigeria, Nsukka (UNN)',
  'University of Port Harcourt (UNIPORT)',
  'University of Uyo (UNIUYO)',
  'Ahmadu Bello University (ABU), Zaria',
  'Alex Ekwueme Federal University, Ndufu-Alike (AE-FUNAI)',
  'Bayero University Kano (BUK)',
  'Federal University, Birnin Kebbi (FUBK)',
  'Federal University, Dutse (FUD)',
  'Federal University, Dutsin-Ma (FUDMA)',
  'Federal University, Gashua (FUGASHUA)',
  'Federal University, Gusau',
  'Federal University, Kashere (FUK)',
  'Federal University, Lafia (FULAF)',
  'Federal University, Lokoja (FULOKOJA)',
  'Federal University, Otuoke',
  'Federal University, Oye-Ekiti (FUOYE)',
  'Federal University, Wukari (FUWUKARI)',
  'Federal University of Petroleum Resources, Effurun (FUPRE)',
  'Federal University of Technology, Akure (FUTA)',
  'Federal University of Technology, Minna (FUTMinna)',
  'Federal University of Technology, Owerri (FUTO)',
  'Michael Okpara University of Agriculture, Umudike (MOUAU)',
  'National Open University of Nigeria (NOUN)',
  'Nigerian Defence Academy (NDA), Kaduna',
  'Nnamdi Azikiwe University (UNIZIK), Awka',
  'Obafemi Awolowo University (OAU), Ile-Ife',
  'Sule Lamido University (SLU), Kafin Hausa',
  'Usmanu Danfodiyo University (UDUS), Sokoto',
  // ─── State Universities ───────────────────────────────────────────────────────
  'Abia State University (ABSU), Uturu',
  'Adamawa State University (ADSU), Mubi',
  'Adekunle Ajasin University (AAUA), Akungba-Akoko',
  'Akwa Ibom State University (AKSU)',
  'Ambrose Alli University (AAU), Ekpoma',
  'Anambra State University (ANSU), Uli',
  'Bauchi State University (BASUG), Gadau',
  'Benue State University (BSU), Makurdi',
  'Confluence University of Science and Technology, Osara',
  'Cross River University of Technology (CRUTECH)',
  'Delta State University (DELSU), Abraka',
  'Ebonyi State University (EBSU), Abakaliki',
  'Ekiti State University (EKSU), Ado-Ekiti',
  'Enugu State University of Science and Technology (ESUT)',
  'Gombe State University (GSU)',
  'Ibrahim Badamasi Babangida University (IBBU), Lapai',
  'Ignatius Ajuru University of Education (IAUE), Port Harcourt',
  'Imo State University (IMSU), Owerri',
  'Kaduna State University (KASU)',
  'Kano University of Science and Technology (KUST), Wudil',
  'Kebbi State University of Science and Technology (KSUSTA)',
  'Kogi State University (KSU), Anyigba',
  'Kwara State University (KWASU), Malete',
  'Ladoke Akintola University of Technology (LAUTECH), Ogbomoso',
  'Lagos State University (LASU)',
  'Lagos State University of Science and Technology (LASUSTECH)',
  'Nasarawa State University (NSUK), Keffi',
  'Niger Delta University (NDU), Wilberforce Island',
  'Ondo State University of Science and Technology (OSUSTECH)',
  'Osun State University (UNIOSUN), Osogbo',
  'Plateau State University (PLASU), Bokkos',
  'Rivers State University (RSU), Port Harcourt',
  'Sokoto State University (SSU)',
  'Tai Solarin University of Education (TASUED), Ijebu-Ode',
  'Taraba State University (TSU), Jalingo',
  'Umaru Musa Yar\'Adua University (UMYU), Katsina',
  'University of Africa (UAT), Toru-Orua',
  'Western Delta University (WDU), Oghara',
  'Yobe State University (YSU), Damaturu',
  'Zamfara State University',
  // ─── Private Universities ─────────────────────────────────────────────────────
  'Adeleke University, Ede',
  'Afe Babalola University (ABUAD), Ado-Ekiti',
  'African University of Science and Technology (AUST), Abuja',
  'Al-Hikmah University, Ilorin',
  'Al-Qalam University, Katsina',
  'American University of Nigeria (AUN), Yola',
  'Anchor University, Lagos',
  'Augustine University, Ilara-Epe',
  'Babcock University, Ilishan-Remo',
  'Baze University, Abuja',
  'Benson Idahosa University (BIU), Benin City',
  'Bowen University, Iwo',
  'Caleb University, Lagos',
  'Capital City University, Kano',
  'Caritas University, Enugu',
  'Chrisland University, Abeokuta',
  'Christopher University, Mowe',
  'Claretian University of Nigeria, Nekede',
  'Coal City University, Enugu',
  'Covenant University (CU), Ota',
  'Crawford University, Igbesa',
  'Crescent University, Abeokuta',
  'Crown Hill University, Eiyenkorin',
  'Dominican University, Ibadan',
  'Edwin Clark University, Kiagbodo',
  'Elizade University, Ilara-Mokin',
  'Evangel University, Akaeze',
  'Fountain University, Osogbo',
  'Godfrey Okoye University, Enugu',
  'Gregory University, Uturu',
  'Hallmark University, Ijebu-Itele',
  'Hezekiah University, Umudi',
  'Igbinedion University, Okada',
  'Joseph Ayo Babalola University (JABU), Ikeji-Arakeji',
  'Kings University, Ode-Omu',
  'Kola Daisi University, Ibadan',
  'Kwararafa University, Wukari',
  'Landmark University, Omu-Aran',
  'Lead City University, Ibadan',
  'Legacy University, Okija',
  'Madonna University, Okija',
  'McPherson University, Seriki Sotayo',
  'Michael and Cecilia Ibru University, Agbarha-Otor',
  'Mountain Top University, Ogun',
  'Nigerian Law School (NLS)',
  'Nile University of Nigeria, Abuja',
  'Novena University, Ogume',
  'Obong University, Obong Ntak',
  'Oduduwa University, Ipetumodu',
  'Pan-Atlantic University (PAU), Lagos',
  'Paul University, Awka',
  'Philomath University, Kuje, Abuja',
  'Precious Cornerstone University, Ibadan',
  'Redeemer\'s University, Ede',
  'Renaissance University, Enugu',
  'Rhema University, Obeama-Asa',
  'Salem University, Lokoja',
  'Samuel Adegboyega University (SAU), Ogwa',
  'Skyline University Nigeria, Kano',
  'Southwestern University Nigeria, Oku Owa',
  'Spiritan University, Nneochi',
  'Summit University, Offa',
  'Tansian University, Umunya',
  'Top Faith University, Mkpatak',
  'Trinity University, Ogun',
  'University of Mkar, Mkar',
  'Veritas University, Abuja',
  'Wesley University, Ondo',
  'Wellspring University, Evbuobanosa',
  'Westland University, Iwo',
  'Other',
] as const;

/** @deprecated Use NIGERIAN_UNIVERSITIES */
export const LAW_SCHOOLS = NIGERIAN_UNIVERSITIES;

export const TOTAL_SPOTS = 100;
export const SPOTS_TAKEN = 40;
export const SPOTS_LEFT = TOTAL_SPOTS - SPOTS_TAKEN;

// ─── Hero copy ────────────────────────────────────────────────────────────────

export const FEATURES = [
  'AI that breaks down any judgment, ratio decidendi, obiter dicta, key principles in plain English.',
  'Exam prep tailored to Nigerian Bar and semester exams with practice questions and model answers.',
  'Search thousands of Nigerian court judgments and legal precedents instantly.',
  'Study guides for contracts, torts, criminal law, constitutional law and more.',
] as const;

export const STATS = [
  { value: '100', label: 'Free Founding Spots' },
  { value: '3+', label: 'Study Tools Built' },
  { value: '0', label: 'Cost to Join' },
] as const;

// ─── Social share ─────────────────────────────────────────────────────────────

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://legalerrand.com';

export const WHATSAPP_SHARE_TEXT =
  `Hey! I just joined the waitlist for LegalErrand Academy — the AI study platform built for law students. Get your free founding member spot before it's gone: ${siteUrl}`;

// ─── Countries (ISO 3166-1) ───────────────────────────────────────────────────

export const COUNTRIES = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'Angola', code: 'AO' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Brazil', code: 'BR' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Congo (DRC)', code: 'CD' },
  { name: "Côte d'Ivoire", code: 'CI' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Greece', code: 'GR' },
  { name: 'Guinea', code: 'GN' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libya', code: 'LY' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Mali', code: 'ML' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Norway', code: 'NO' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russia', code: 'RU' },
  { name: 'Rwanda', code: 'RW' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Korea', code: 'KR' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Tanzania', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Togo', code: 'TG' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Vietnam', code: 'VN' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
] as const;

export type CountryCode = (typeof COUNTRIES)[number]['code'];
